import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NavBar } from "@/components/nav-bar";
import { SearchBar } from "@/components/search-bar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className=" flex justify-center">
          <div className=" w-full max-w-6xl">
            <NavBar />
            <SearchBar/>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
